/* eslint-disable simple-import-sort/imports */
import { ConfigProvider } from 'antd';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { SideMenu } from '@/components';
import { AntdRegistry } from '@ant-design/nextjs-registry';

import DataTablesProvider from '@/context/DataTablesContext';
import LayoutProvider from '@/context/LayoutContext';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sagala Dashboard | Rezki Triandy',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-cyan-50">
        <AntdRegistry>
          <ConfigProvider
            theme={{
              components: {
                Button: {
                  defaultBg: '#ecfeff',
                  colorText: '#422AFB'
                },
                Progress: {
                  defaultColor: '#422AFB'
                }
              },
              token: {
                colorPrimary: '#422AFB'
              }
            }}
          >
            <LayoutProvider>
              <DataTablesProvider>
                <div className="flex min-h-screen">
                  <SideMenu />
                  <div className="max-h-screen flex-1 overflow-auto px-8 py-8">{children}</div>
                </div>
              </DataTablesProvider>
            </LayoutProvider>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
