/* eslint-disable simple-import-sort/imports */
import { ConfigProvider } from 'antd';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { PageHeader, SideMenu } from '@/components';
import { AntdRegistry } from '@ant-design/nextjs-registry';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sagala Dashboard | Rezki Triandy',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-cyan-50">
        <AntdRegistry>
          <ConfigProvider
            theme={{
              components: {
                Button: {
                  defaultBg: '#ecfeff',
                  colorText: '#422AFB'
                },
                Input: {
                  colorBgContainer: '#f0f9ff',
                  lineWidth: 0,
                  controlHeight: 38
                },
                Progress: {
                  defaultColor: '#422AFB'
                }
              }
            }}
          >
            <div className="flex min-h-screen">
              <SideMenu />
              <div className="max-h-screen flex-1 overflow-auto px-8 py-8">
                <PageHeader />
                {children}
              </div>
            </div>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
